version: "3.8"
services:
  dev:
    build: .
    #environment:
    #  SSH_USER: "${USER}"
    network_mode: "bridge"
    #network: host
    privileged: false
    volumes:
      - "./site/:/site/"
    ports:
      - "1313:1313"