baseURL = "https://www.asixor.com"
title = "Asixor"
author = "Asixor"
languageCode = "es"
DefaultContentLanguage = "es"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.jpg"
    alt = "Asixor"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Asixor"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Asixor es su aliado estratégico en el comercio exterior"
    meta_og_title = "Asixor"
    meta_og_type = "website"
    meta_og_url = "https://www.asixor.com"
    #meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Asixor es su aliado estratégico en el comercio exterior"
    #meta_twitter_card = "summary_large_image"
    #meta_twitter_site = "@username"
    #meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "inicio"
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "servicios"
    name = "Servicios"
    url = "/products/"
    weight = 2

  [[menu.main]]
    identifier = "sobre-nosotros"
    name = "Sobre nosotros"
    url = "/sobre-nosotros/"
    weight = 3

  [[menu.main]]
    identifier = "contactenos"
    name = "Contactenos"
    url = "/contactenos/"
    weight = 4

  #[[menu.main]]
  #  identifier = "blog"
  #  name = "Blog"
  #  url = "/blog/"
  #  weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Inicio"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Whatsapp +54 9 3416 29-7342"
    url = "https://wa.me/qr/ZKL3DFGG5GNKJ1"
      weight = 2
